---
- name: Basic creation and ssh-key setup for a user
  hosts: remote_hosts
  vars:
    user_name: ""
  tasks:

    - name: Set user as fact
      ansible.builtin.set_fact:
        user_name: "{{ user_name | default('ansible') }}"

    - name: Ensure {{ user_name }} is present on {{ inventory_hostname }}
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: true
      become: true

    - name: Ensure .ssh folder is present for user {{ user_name }}
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: 0700
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Create ssh key pair for user {{ user_name }}
      community.crypto.openssh_keypair:
        path: ~/.ssh/{{ ssh_key | default('id_rsa') }}
        mode: 0600
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: Retrieve public key for user {{ user_name }}  and store it
      ansible.builtin.slurp:
        path: ~/.ssh/id_rsa.pub
      register: public_key
      delegate_to: localhost

    - name: Authorize current user key on {{ inventory_hostname }} for user {{ user_name }}
      become: true
      ansible.posix.authorized_key:
        user: "{{ user_name }}"
        key: "{{ public_key.content | b64decode }}"
        state: present

    - name: Enable sudo access for user {{ user_name }}
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ user_name }}
        line: "{{ user_name }}   ALL=(ALL)       NOPASSWD: ALL"
        mode: 0600
        owner: root
        group: root
        create: true